language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "12"

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    reciepients:
      - luissol@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: apiKey # desde heroku
  app: platzi-store1-back
  on:
    repo: raytho/platzi-store-backend
